### ISSUE TITLE
An administrator cannot view job logs for other users

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#40]
As per https://github.com/kbase/execution_engine2/issues/220

An administrator cannot view job logs for other users. (The fix for this is to pass "as_admin"  = True, if user is admin)

**Comment by eapearson** [comment]
This is fixed now, at around
https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/0305485f254b02afa4c55f01c569d8cd171412fe
