### ISSUE TITLE
Fix Downloads/Subjobs not showing App Name

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#41]
![image](https://user-images.githubusercontent.com/1258634/79506094-07a51680-7ffb-11ea-950c-21589db701b7.png)
* This job is not a subjob a.k.a parallel job, its just a download job
* Fix Downloads/Subjobs not showing App Name as per the screenshot

**Comment by bio-boris** [comment]
Checkjob for that job id 5e989b832dd34ccf152fd3f4 is 

```
{'authstrat': 'kbaseworkspace',
 'created': 1587059587000,
 'finished': 1587059762630,
 'job_id': '5e989b832dd34ccf152fd3f4',
 'job_input': {'app_id': 'AssemblyUtil.export_assembly_as_fasta',
               'method': 'AssemblyUtil.export_assembly_as_fasta',
               'narrative_cell_info': {},
               'params': [{'input_ref': '60101/3'}],
               'parent_job_id': 'None',
               'requirements': {'clientgroup': 'njs',
                                'cpu': 4,
                                'disk': 100,
                                'memory': 23000},
               'service_ver': 'release',
               'source_ws_objects': []},
 'job_output': {'id': '5e989b832dd34ccf152fd3f4',
                'result': [{'shock_id': '295bebc7-9fda-4d28-b59a-169fa0b9d314'}],
                'version': '1.1'},
 'queued': 1587059588576,
 'running': 1587059621631,
 'scheduler_id': '335189',
 'scheduler_type': 'condor',
 'status': 'completed',
 'updated': 1587059762630,
 'user': 'bsadkhin'}
```

**Comment by eapearson** [comment]
I see, this isn't detected as an export job, so it default to "unknown" job type. I'm working on a fix.

**Comment by eapearson** [comment]
This should be much improved, at about

https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/3c83b202bb21445eec0ddf3b6516f3d2d8281098

The fix is both front end and the back end bff. For non-narrative jobs, app column does not render a link, since there is no catalog view for non-narrative methods. The method is displayed without a link.
