### ISSUE TITLE
Wrong "Server" info

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#43]
Some apps display this :kb_upload,request_cpus=1,request_memory=6000 . They should instead display NJS or whatever is stored in the ee2 database. I do not think it is useful to see that, but it could actually be useful for the user to know how much cpu/memory/disk the job requested and actually used though. Or maybe show other interesting stats from `check_job`

**Comment by eapearson** [comment]
@bio-boris Hey, can you evaluate this again with the current state of the job browser?
The "server" (if you have a better user term for this, I'd be happy to change it) info is now taken from the job state `job_input.requirements.clientgroup`. Previously it was taken from the app.
btw do you know if there are user-facing documents to explain the kbase ee? That could be where we establish the user-facing terminology. 

I agree we should enhance the insight a user can get into ee for their jobs -- the resource constraints, actual resource usage, live queue status, I imagine would be very helpful for experienced users, users who are familiar with running the wrapped apps standalone and know their performance characteristics under different resource conditions.

**Comment by bio-boris** [comment]
I don't think that just showing cgroups is useful. I think the entire job requirements should be displayed. If just the clientgroup is being displayed we should drop this column for now. I think instead there should be a mini table in that cell that shows
request_cpus, (cpu_used) those this field is not yet working
request_memory, memory_used (ResidentSetSize is saved upon successful job completion)
request_disk, disk_used
resource_type, njs/bigmem/bigmemlong

User facing info that I know about:  Only here https://kbase.github.io/kb_sdk_docs/references/execution_engine.html and on the queue page.

**Comment by bio-boris** [comment]
client groups are used as a filter so this is fine
