### ISSUE TITLE
10 second timeout for admin jobs listing.

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#44]
After 10 second timeout for admin jobs listing, and nothing happens. You have to refresh the page

**Comment by bio-boris** [comment]
Can't use it on appdev, 

![image](https://user-images.githubusercontent.com/1258634/80854945-e8fd6d00-8c01-11ea-99f6-e5ebd69eda7c.png)

**Comment by eapearson** [comment]
The timeout for all network api calls has been increased to 60 seconds. It is globally set, although not yet configurable, https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/2a8df05e1c3a9a83d4a3044a2f5f63193740a006.
This is now in the develop image.
