### ISSUE TITLE
Next Page and Page numbers below take you to non existent pages of the job browser.

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#45]
You can click on "next page" or the numbers below and it takes you to a place that really isnt there..

**Comment by eapearson** [comment]
I don't know what was happening, but the table implementation has been replaced. The original paged ant design table, which had page selection as well as navigation, has been replaced with a custom table which automatically resizes the table when the browser window is resized. That implementation has it's own bugs, but not this one!
