### ISSUE TITLE
inaccessible workspace

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#56]
`inaccessible workspace` or `unknown` message is for most jobs on ci. This seems like an inefficient use of a column. Can we move this to the tab for the log viewer maybe? I would rather see the full name of the app or other info about the job.

**Comment by eapearson** [comment]
The narrative column has been removed for the user jobs tab:

https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/054c632d5a341635cd33aaf5b54e3aa67dc316d3

Now the apps column can breathe!
