### ISSUE TITLE
Client group filter dropdown does not list client groups

### ISSUE THREAD

**Issue by eapearson** [kbase/kbase-ui-plugin-job-browser2#63]
The client group filter dropdown is incomplete and needs to be finished.
@bio-boris we discussed how the server/client group filter could be populated from an ee2 call. otherwise, the values for the dropdown will need to be hardcoded somewhere (bff, probably).
Do you think it is reasonable for ee2 to provide an api method to return a list of available client groups? I don't know if this is available already in the db or a config file, or if it would be better to implement it as a query over existing jobs, returning unique values.
Or we could change the implementation on the browser side to provide this filter as a text input. The user would need to be aware of which client groups exist, and their spelling.
Or, the dropdown of client groups could provide for a free-text override.

**Comment by bio-boris** [comment]
Yes, I have added it on CI
```
        /* Get a list of clientgroups manually extracted from the config file */
        funcdef get_client_groups() returns (list<string> client_groups) authentication required;
```

**Comment by eapearson** [comment]
The client groups filter derives values from the ee2 source now (well, as of the following commit, which was a while ago)
https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/a470021b2a760c155956fe1d1105a6c1fb31a721
