### ISSUE TITLE
Date Range Issues

### ISSUE THREAD

**Issue by bio-boris** [kbase/kbase-ui-plugin-job-browser2#73]
* Crashes without a normal message when choosing a start date after the end date for date range search

```
Choose 2020-05-27 02:17:12 to 2020-05-28 12:17:12
Click Last Page
Then choose Error
It takes you to page 63 of 16, when there are only 16 pages... This makes you show 0 results
```

**Comment by eapearson** [comment]
Switched from two DatePicker controls to one RangePicker control. The range picker makes it impossible for a user to specify an end datetime before the start.
https://github.com/kbase/kbase-ui-plugin-job-browser2/commit/9c814e30fc3a04e7a69da095a71ca15e0ae44626
